version: "3.8"

services:
  backend:
    image: money-transfer:1.0
    ports:
      - 5500
    build: ./
    environment:
      TEST: env_money_transfer
  frontend:
    image: card-transfer-frontend:1.0
    environment:
      PORT: 3000
      PROXY_API: http://localhost:3000/
    ports:
      - 3000:3000